version: '3.8'

services:
  reverse.proxy:
    image: traefik:v2.9
    container_name: reverse.proxy
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --log.level=DEBUG
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.address=:80
      - --certificatesresolvers.letsencrypt.acme.email=<YOUR_EMAIL_ADDRESS> # <-- Change this
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      #- --certificatesresolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=azure
    environment:
      - AZURE_ENVIRONMENT=<AZURE_ENVIRONMENT> # <-- Change this
      - AZURE_RESOURCE_GROUP=<YOUR_RESOURCE_GROUP_NAME> # <-- Change this
      - AZURE_ZONE_NAME=<YOUR_DNS_ZONE_NAME> # <-- Change this
      - AZURE_SUBSCRIPTION_ID=<YOUR_AZURE_SUBSCRIPTION_NAME> # <-- Change this
      - AZURE_TENANT_ID=<YOUR_AZURE_TENANT_ID> # <-- Change this
      - AZURE_CLIENT_ID=<YOUR_APP_CLIENT_ID> # <-- Change this
      - AZURE_CLIENT_SECRET=<YOUR_APP_CLIENT_SECRET> # <-- Change this
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik:/letsencrypt
    restart:
      unless-stopped

  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.<YOUR_DOAMIN_NAME>`) # <-- Change this
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=letsencrypt
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80

volumes:
  traefik: