version: '3.4'

services:

  cosmosdbtest:
    entrypoint: sh -c 'sleep 5 && apt-get update && apt-get install -y curl && curl -k https://azure.cosmosdb:8081/_explorer/emulator.pem > /usr/local/share/ca-certificates/azure.cosmosdb.crt && update-ca-certificates && tail -f /dev/null'
    depends_on:
      - azure.cosmosdb

  # Emulator portal https://localhost:8081/_explorer/index.html
  azure.cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: azure.cosmosdb
   # mem_limit: 3g
   # cpus: 2.0
    hostname: azure.cosmosdb
    environment:
       - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5 
       - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
       - 8081:8081 
       - 10251:10251 
       - 10252:10252 
       - 10253:10253 
       - 10254:10254
